title: IT3090 - THỰC HÀNH
logo: /assets/img/microsoft-sql-server.svg
description: Trang web tài liệu thực thành cho khóa IT3090 Cơ Sở Dữ Liệu
show_downloads: true
document_download: /assets/course-materials/BaiThucHanh_2019.zip
google_analytics:
theme: jekyll-theme-minimal
